'use client';

import { useState } from 'react';
import { DoctorSummary as DoctorSummaryType, Severity } from '@/types';
import { SEVERITY_CONFIG } from '@/lib/constants';

interface DoctorSummaryProps {
  summary: DoctorSummaryType;
  severity: Severity;
  symptoms: string[];
}

export default function DoctorSummary({
  summary,
  severity,
  symptoms,
}: DoctorSummaryProps) {
  const [copied, setCopied] = useState(false);
  const config = SEVERITY_CONFIG[severity];

  // Detect if English and local are the same (e.g. when language is English)
  const isDuplicate =
    summary.english.trim().toLowerCase() === summary.local.trim().toLowerCase();

  const handleCopy = async () => {
    const text = isDuplicate
      ? `--- Sehat AI Triage Summary ---\nSeverity: ${config.label}\nSymptoms: ${symptoms.join(', ')}\n\nClinical Summary:\n${summary.english}\n\n--- Generated by Sehat AI Triage. Not a medical diagnosis. ---`
      : `--- Sehat AI Triage Summary ---\nSeverity: ${config.label}\nSymptoms: ${symptoms.join(', ')}\n\nClinical Summary (English):\n${summary.english}\n\nClinical Summary (Patient's Language):\n${summary.local}\n\n--- Generated by Sehat AI Triage. Not a medical diagnosis. ---`;
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="doctor-summary w-full bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden animate-slide-up">
      {/* Header */}
      <div className="bg-gray-50 px-5 py-3 border-b border-gray-200 flex items-center gap-2">
        <svg
          className="w-5 h-5 text-teal-600"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z"
          />
        </svg>
        <h3 className="font-semibold text-gray-700">Doctor Summary</h3>
        <span className="text-xs text-gray-400 ml-auto">Show this to your doctor</span>
      </div>

      {/* Content */}
      <div className="p-5 space-y-4">
        {/* Severity badge */}
        <div className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-sm font-semibold ${config.bgColor} ${config.textColor}`}>
          <span aria-hidden="true">{config.icon}</span> {config.label}
        </div>

        {/* Symptoms */}
        <div>
          <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">
            Reported Symptoms
          </h4>
          <p className="text-sm text-gray-700">{symptoms.join(', ')}</p>
        </div>

        {/* English summary (always shown) */}
        <div>
          <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">
            {isDuplicate ? 'Clinical Summary' : 'Clinical Summary (English)'}
          </h4>
          <p className="text-sm text-gray-800 leading-relaxed bg-gray-50 rounded-lg p-3">
            {summary.english}
          </p>
        </div>

        {/* Local language summary — only shown when different from English */}
        {!isDuplicate && (
          <div>
            <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-1">
              Clinical Summary (Patient&apos;s Language)
            </h4>
            <p className="text-sm text-gray-800 leading-relaxed bg-gray-50 rounded-lg p-3">
              {summary.local}
            </p>
          </div>
        )}

        {/* Disclaimer */}
        <p className="text-xs text-gray-400 italic">
          AI-assisted triage — not a medical diagnosis. Generated by Sehat.
        </p>
      </div>

      {/* Action buttons */}
      <div className="no-print flex gap-2 px-5 py-3 border-t border-gray-100 bg-gray-50">
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-4 py-2 text-sm font-medium text-teal-700
                     bg-teal-50 rounded-lg hover:bg-teal-100 transition-colors active:scale-95"
        >
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
          </svg>
          {copied ? 'Copied!' : 'Copy'}
        </button>
        <button
          onClick={handlePrint}
          className="flex items-center gap-1.5 px-4 py-2 text-sm font-medium text-gray-700
                     bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors active:scale-95"
        >
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5Zm-3 0h.008v.008H15V10.5Z" />
          </svg>
          Print
        </button>
      </div>
    </div>
  );
}
